ElaWorkshop/awesome-cn-cafe

- beijing.geojson
添加准确的坐标太痛苦了，Google Maps 给的坐标值和Mapbox（可能没有做中国特色修正？）认的有偏差。
> Beijing: Add "May Café"

- README.md
- beijing.geojson
> add esquires

- README.md
- shanghai.geojson
Hi there! I've visited three cafés since the last PR, here they are:
- Staytion Coffee & Bake
- Pacific Coffee at Global Harbor
- CAFÉ & BAR PRONTO
:D
> Add three cafes in Shanghai.

- nanjing.geojson
> 新增南京 The Cub

- README.md
- shanghai.geojson
- Costa (Global Harbor)
- SeeSaw (淮海 755)
- Costa (九六广场)
> Add 3 cafes in Shanghai

- README.md
> Fix color value in readme

- README.md
- hangzhou.geojson
- shanghai.geojson
Also update some issues by re-running the housekeeper script.
> Add starbucks(Caohejing)

- shanghai.geojson
> Add mangosix jingan & aunn cafe & co.

- README.md
> Set speedtest app as the recommended way to get speed and coordinates in mobile

- README.md
- beijing.geojson
The location of the cafe in this PR is just next to the cafe #69 .
So it looks almost in the same place unless zoom in.
> Add COSTA Coffee (Full-link)

- README.md
- beijing.geojson
> Add Cafe Flatwhite(Huamao)

- README.md
- beijing.geojson
> Remove May Cafe

- README.md
- beijing.geojson
> Seesaw Coffee @ WF Central

- .travis.yml
- tools/README.md
- tools/housekeeper.js
- tools/lint.js
- tools/package.json
- Add automatic update for the cafe number in README.md with housekeeper
> - Minor refactoring

- README.md
- shanghai.geojson
~- Remove Caffebene(closed)~
- Mark Caffebene as closed.
- Add Periwinkle
> Add Periwinkle

- README.md
- beijing.geojson
> Guell cafe

- README.md
- shanghai.geojson
> Add mstand

- shanghai.geojson
> Tan coffee

- shanghai.geojson
> Akimbo cafe

- README.md
- changsha.geojson
> add a new cafe in Changsha

- README.md
- shanghai.geojson
> Delete: 移除三家因拆迁而歇业的咖啡店

- README.md
- chongqing.geojson
Hello,
This is my contribution to this repository.
Please find an entry for Chongqing GeoJSON with Maan Coffee 漫咖啡 of Chongqing added.
I might record more later of Chongqing as this repository is really lacking information about this province. 😄 
Thank you.
Note: the latitude and longitude were retrieved using online Chinese maps.
> Add: Maan Coffee @ Chongqing MixC / 星巴克 Starbucks @ 重庆袁家岗K-Land店

- beijing.geojson
> Deactivate TOSCA

- README.md
- nanjing.geojson
> add a new cafe for nanjing
